### ISSUE TITLE
Errors upgrading from Dojo 3 to Dojo 4

### ISSUE THREAD

**Issue by evra** [dojo/cli-upgrade-app#21]
I got following errors while trying to upgrade from v3 to v4

`i Running transform: Move deleted core dependencies into codebase

 ERR src/BaseApp.ts Transformation error
TypeError: dependencies[filePath] is not iterable
    at NodePath.j.find.replaceWith (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:17:59)
    at NodePath.<anonymous> (C:\myProject\node_modules\jscodeshift-ts\src\collections\Node.js:144:47)
    at __paths.forEach (C:\myProject\node_modules\jscodeshift-ts\src\Collection.js:76:36)
    at Array.forEach (<anonymous>)
    at Collection.forEach (C:\myProject\node_modules\jscodeshift-ts\src\Collection.js:75:18)
    at Collection.replaceWith (C:\myProject\node_modules\jscodeshift-ts\src\collections\Node.js:142:17)
    at Collection.typedMethod [as replaceWith] (C:\myProject\node_modules\jscodeshift-ts\src\Collection.js:400:43)
    at module.exports (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:12:10)
 ERR src/widgets/simpleGrid/GridSettings.ts Transformation error
Error: EPERM: operation not permitted, copyfile 'C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\core\lang.ts' -> 'C:\myProject\src\dojo\core\lang.ts'
    at Object.fs.copyFileSync (fs.js:1918:11)
    at copyFile (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:66:8)
    at mayCopyFile (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:58:12)
    at onFile (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:52:10)
    at getStats (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:46:44)
    at startCopy (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:36:10)
    at Object.copySync (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:31:10)
    at filesToCopy.forEach (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:20:24)
    at Array.forEach (<anonymous>)
    at NodePath.j.find.replaceWith (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:18:25)
 ERR tests/support/HttpMock.ts Transformation error
Error: EBUSY: resource busy or locked, unlink 'C:\myProject\src\dojo\core\interfaces.ts'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at mayCopyFile (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:57:8)
    at onFile (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:52:10)
    at getStats (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:46:44)
    at startCopy (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:36:10)
    at Object.copySync (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:31:10)
    at filesToCopy.forEach (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:20:24)
    at Array.forEach (<anonymous>)
    at NodePath.j.find.replaceWith (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:18:25)
    at NodePath.<anonymous> (C:\myProject\node_modules\jscodeshift-ts\src\collections\Node.js:144:47)
 ERR tests/unit/BaseApp.ts Transformation error
Error: EBUSY: resource busy or locked, unlink 'C:\myProject\src\dojo\core\lang.ts'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at mayCopyFile (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:57:8)
    at onFile (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:52:10)
    at getStats (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:46:44)
    at startCopy (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:36:10)
    at Object.copySync (C:\myProject\node_modules\@dojo\cli-upgrade-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:31:10)
    at filesToCopy.forEach (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:20:24)
    at Array.forEach (<anonymous>)
    at NodePath.j.find.replaceWith (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:18:25)
    at NodePath.<anonymous> (C:\myProject\node_modules\jscodeshift-ts\src\collections\Node.js:144:47)
 ERR src/rest/SQMSRestClient.ts Transformation error
TypeError: dependencies[filePath] is not iterable
    at NodePath.j.find.replaceWith (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:17:59)
    at NodePath.<anonymous> (C:\myProject\node_modules\jscodeshift-ts\src\collections\Node.js:144:47)
    at __paths.forEach (C:\myProject\node_modules\jscodeshift-ts\src\Collection.js:76:36)
    at Array.forEach (<anonymous>)
    at Collection.forEach (C:\myProject\node_modules\jscodeshift-ts\src\Collection.js:75:18)
    at Collection.replaceWith (C:\myProject\node_modules\jscodeshift-ts\src\collections\Node.js:142:17)
    at Collection.typedMethod [as replaceWith] (C:\myProject\node_modules\jscodeshift-ts\src\Collection.js:400:43)
    at module.exports (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:12:10)
 ERR tests/unit/rest/SQMSRestClient.ts Transformation error
TypeError: dependencies[filePath] is not iterable
    at NodePath.j.find.replaceWith (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:17:59)
    at NodePath.<anonymous> (C:\myProject\node_modules\jscodeshift-ts\src\collections\Node.js:144:47)
    at __paths.forEach (C:\myProject\node_modules\jscodeshift-ts\src\Collection.js:76:36)
    at Array.forEach (<anonymous>)
    at Collection.forEach (C:\myProject\node_modules\jscodeshift-ts\src\Collection.js:75:18)
    at Collection.replaceWith (C:\myProject\node_modules\jscodeshift-ts\src\collections\Node.js:142:17)
    at Collection.typedMethod [as replaceWith] (C:\myProject\node_modules\jscodeshift-ts\src\Collection.js:400:43)
    at module.exports (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:12:10)

√  transform complete.
6 Errors 11 OK 1 Skipped 232 Unchanged`

**Comment by evra** [comment]
my package.json: 

```json
`"dependencies": {
	"@dojo/framework": "^3.0.1",
    "@dojo/cli-upgrade-app": "^4.0.1",
    "cldr-core": "33.0.0",
    "cldr-dates-modern": "33.0.0",
    "cldr-numbers-modern": "33.0.0",
    "cldr-units-modern": "33.0.0"
  },
  "devDependencies": {
    "@dojo/cli": "~3.0.0",
    "@dojo/cli-build-app": "3.0.3",
    "@dojo/cli-test-intern": "3.0.0",
    "@dojo/framework": "^3.0.1",
    "@dojo/loader": "2.0.0",
    "@dojo/themes": "3.0.1",
    "@dojo/widgets": "3.0.0",
    "@types/glob": "~5.0.35",
    "@types/grunt": "~0.4.0",
    "@types/node": "^8.0.0",
    "@types/sinon": "~4.3.0",
    "copyfiles": "2.0.0",
    "execa": "^0.9.0",
    "grunt": "^1.0.1",
    "grunt-contrib-clean": "^2.0.0",
    "grunt-contrib-watch": "^1.1.0",
    "grunt-dojo2": "~0.1.3",
    "grunt-exec": "^3.0.0",
    "grunt-tslint": "^5.0.1",
    "intern": "4.3.1",
    "load-grunt-tasks": "^3.5.2",
    "pkg-dir": "^2.0.0",
    "shx": "^0.2.2",
    "sinon": "~4.5.0",
    "sonarqube-scanner": "^2.0.2",
    "ts-node": "^3.3.0",
    "tslint": "5.9.1",
    "typescript": "~2.6.2"
  },`
