### ISSUE TITLE
Fix support for the d.ts files

### ISSUE THREAD

**Issue by evra** [dojo/cli-upgrade-app#23]
While running upgrade from v3 to v4 I got the following error
```
ERR src/BaseApp.ts Transformation error
TypeError: dependencies[filePath] is not iterable
    at NodePath.j.find.replaceWith (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:17:59)
    at NodePath.<anonymous> (C:\myProject\node_modules\jscodeshift-ts\src\collections\Node.js:144:47)
    at __paths.forEach (C:\myProject\node_modules\jscodeshift-ts\src\Collection.js:76:36)
    at Array.forEach (<anonymous>)
    at Collection.forEach (C:\myProject\node_modules\jscodeshift-ts\src\Collection.js:75:18)
    at Collection.replaceWith (C:\myProject\node_modules\jscodeshift-ts\src\collections\Node.js:142:17)
    at Collection.typedMethod [as replaceWith] (C:\myProject\node_modules\jscodeshift-ts\src\Collection.js:400:43)
    at module.exports (C:\myProject\node_modules\@dojo\cli-upgrade-app\v4\transforms\replace-legacy-core.js:12:10)
```

If the import `import { Response } from '@dojo/framework/core/request/interfaces';` is removed from the  `BaseApp.ts` then no error appears.

According to @agubler  this is an issue with the `d.ts` files support.

**Comment by agubler** [comment]
Resolved by https://github.com/dojo/cli-upgrade-app/pull/24
